#!/usr/bin/env python3
"""
scripts/reset_regime_neutral.py — Сброс режима в нейтраль

Когда использовать:
  - Файл режима устарел (> 24h) и оркестратор недоступен
  - Рынок неопределён — хотим дать всем стратегиям работать
  - Быстрый reset без перезапуска бота (бот hot-reload файла каждые 5 мин)

Usage:
  python3 scripts/reset_regime_neutral.py
  python3 scripts/reset_regime_neutral.py --regime bull_chop  # или bear_chop / bull_trend / bear_trend
  python3 scripts/reset_regime_neutral.py --dry-run           # показать без записи
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

ENV_PATH  = ROOT / "configs" / "regime_orchestrator_latest.env"
JSON_PATH = ROOT / "runtime" / "regime" / "orchestrator_state.json"

VALID_REGIMES = {"neutral", "bull_trend", "bull_chop", "bear_trend", "bear_chop"}

REGIME_PRESETS = {
    "neutral": {
        "allow_longs": True, "allow_shorts": True,
        "global_risk_mult": 0.75,
        "risk_level": 2,
        "enable_breakout": True,
        "enable_breakdown": True,
        "enable_flat": True,
        "enable_midterm": True,
        "note": "Neutral — all strategies enabled, reduced risk",
    },
    "bull_trend": {
        "allow_longs": True, "allow_shorts": False,
        "global_risk_mult": 1.0,
        "risk_level": 1,
        "enable_breakout": True,
        "enable_breakdown": False,
        "enable_flat": True,
        "enable_midterm": True,
        "note": "Bull trend — longs only, full risk",
    },
    "bull_chop": {
        "allow_longs": True, "allow_shorts": False,
        "global_risk_mult": 0.75,
        "risk_level": 2,
        "enable_breakout": True,
        "enable_breakdown": False,
        "enable_flat": True,
        "enable_midterm": True,
        "note": "Bull chop — longs only, reduced risk",
    },
    "bear_trend": {
        "allow_longs": False, "allow_shorts": True,
        "global_risk_mult": 0.85,
        "risk_level": 3,
        "enable_breakout": False,
        "enable_breakdown": True,
        "enable_flat": True,
        "enable_midterm": True,
        "note": "Bear trend — shorts only",
    },
    "bear_chop": {
        "allow_longs": False, "allow_shorts": True,
        "global_risk_mult": 0.70,
        "risk_level": 3,
        "enable_breakout": False,
        "enable_breakdown": True,
        "enable_flat": True,
        "enable_midterm": True,
        "note": "Bear chop — shorts only, lowest risk",
    },
}


def build_env(regime: str, preset: dict, ts: str) -> str:
    lines = [
        f"# Auto-generated by reset_regime_neutral.py at {ts}",
        f"ORCH_STATE_VERSION=1",
        f"ORCH_GENERATED_AT_UTC={ts}",
        f"ORCH_REGIME={regime}",
        f"ORCH_RAW_REGIME={regime}",
        f"ORCH_PENDING_REGIME={regime}",
        f"ORCH_PENDING_COUNT=0",
        f"ORCH_CONFIDENCE=0.5",
        f"ORCH_GLOBAL_RISK_MULT={preset['global_risk_mult']}",
        f"ORCH_RISK_LEVEL={preset['risk_level']}",
        f"# Strategy enables",
        f"ENABLE_BREAKOUT_TRADING={'1' if preset['enable_breakout'] else '0'}",
        f"BREAKOUT_ALLOW_LONGS={'1' if preset['allow_longs'] else '0'}",
        f"BREAKOUT_ALLOW_SHORTS={'1' if preset['allow_shorts'] else '0'}",
        f"ENABLE_BREAKDOWN_TRADING={'1' if preset['enable_breakdown'] else '0'}",
        f"ENABLE_FLAT_TRADING={'1' if preset['enable_flat'] else '0'}",
        f"ENABLE_MIDTERM_TRADING={'1' if preset['enable_midterm'] else '0'}",
    ]
    return "\n".join(lines) + "\n"


def build_json(regime: str, preset: dict, ts: str) -> dict:
    return {
        "version": 1,
        "timestamp_utc": ts,
        "ts_utc": ts,
        "regime": regime,
        "raw_regime": regime,
        "pending_regime": regime,
        "pending_count": 0,
        "regime_changed": False,
        "previous_regime": "unknown",
        "confidence": 0.5,
        "btc_bias": "neutral",
        "risk_level": preset["risk_level"],
        "global_risk_mult": preset["global_risk_mult"],
        "notes": [preset["note"], "Set by reset_regime_neutral.py"],
        "strategy_overrides": {
            "ENABLE_BREAKOUT_TRADING": "1" if preset["enable_breakout"] else "0",
            "BREAKOUT_ALLOW_LONGS": "1" if preset["allow_longs"] else "0",
            "BREAKOUT_ALLOW_SHORTS": "1" if preset["allow_shorts"] else "0",
            "ENABLE_BREAKDOWN_TRADING": "1" if preset["enable_breakdown"] else "0",
            "ENABLE_FLAT_TRADING": "1" if preset["enable_flat"] else "0",
            "ENABLE_MIDTERM_TRADING": "1" if preset["enable_midterm"] else "0",
            "ORCH_REGIME": regime,
            "ORCH_CONFIDENCE": "0.5",
            "ORCH_RAW_REGIME": regime,
            "ORCH_PENDING_REGIME": regime,
            "ORCH_PENDING_COUNT": "0",
            "ORCH_GENERATED_AT_UTC": ts,
            "ORCH_STATE_VERSION": "1",
        },
        "sleeves": {"momentum": "off", "mean_reversion": "active", "swing": "active"},
        "indicators": {},
        "state_path": str(JSON_PATH),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Reset regime to neutral (or specified regime)")
    ap.add_argument("--regime", default="neutral", choices=list(VALID_REGIMES))
    ap.add_argument("--dry-run", action="store_true", help="Print without writing")
    args = ap.parse_args()

    preset = REGIME_PRESETS[args.regime]
    ts = datetime.now(timezone.utc).isoformat()

    env_content  = build_env(args.regime, preset, ts)
    json_content = build_json(args.regime, preset, ts)

    print(f"{'[DRY RUN] ' if args.dry_run else ''}Regime → {args.regime.upper()}")
    print(f"  allow_longs={preset['allow_longs']} allow_shorts={preset['allow_shorts']}")
    print(f"  risk_mult={preset['global_risk_mult']} risk_level={preset['risk_level']}")
    print(f"  note: {preset['note']}")
    print()

    if args.dry_run:
        print("─── .env content ───")
        print(env_content)
        return

    # Write env file (atomic via temp)
    tmp_env = ENV_PATH.with_suffix(".env.tmp")
    tmp_env.write_text(env_content)
    tmp_env.replace(ENV_PATH)
    print(f"✅ Written: {ENV_PATH}")

    # Write JSON state
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp_json = JSON_PATH.with_suffix(".json.tmp")
    tmp_json.write_text(json.dumps(json_content, indent=2))
    tmp_json.replace(JSON_PATH)
    print(f"✅ Written: {JSON_PATH}")

    print()
    print("Bot will hot-reload within 5 minutes (REGIME_OVERLAY_RELOAD_SEC=300).")
    print("To apply immediately: send /reload_regime to Telegram or restart bot.")


if __name__ == "__main__":
    main()
