#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BASE_ENV="${ALPACA_BASE_LOCAL_ENV:-$ROOT/configs/alpaca_paper_local.env}"
CANDIDATE_ENV="${ALPACA_CANDIDATE_ENV:-$ROOT/configs/alpaca_paper_v36_candidate.env}"

OVERRIDE_ALPACA_SEND_ORDERS="${ALPACA_SEND_ORDERS-}"
OVERRIDE_ALPACA_CLOSE_STALE_POSITIONS="${ALPACA_CLOSE_STALE_POSITIONS-}"
OVERRIDE_ALPACA_AUTOPILOT_REFRESH="${ALPACA_AUTOPILOT_REFRESH-}"
OVERRIDE_ALPACA_AUTOPILOT_REFRESH_SCRIPT="${ALPACA_AUTOPILOT_REFRESH_SCRIPT-}"
OVERRIDE_ALPACA_AUTOPILOT_RUNTIME_DIR="${ALPACA_AUTOPILOT_RUNTIME_DIR-}"
OVERRIDE_ALPACA_PICKS_CSV="${ALPACA_PICKS_CSV-}"

if [[ -f "$BASE_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$BASE_ENV"
  set +a
fi

if [[ -f "$CANDIDATE_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$CANDIDATE_ENV"
  set +a
fi

if [[ -n "$OVERRIDE_ALPACA_SEND_ORDERS" ]]; then
  export ALPACA_SEND_ORDERS="$OVERRIDE_ALPACA_SEND_ORDERS"
fi
if [[ -n "$OVERRIDE_ALPACA_CLOSE_STALE_POSITIONS" ]]; then
  export ALPACA_CLOSE_STALE_POSITIONS="$OVERRIDE_ALPACA_CLOSE_STALE_POSITIONS"
fi
if [[ -n "$OVERRIDE_ALPACA_AUTOPILOT_REFRESH" ]]; then
  export ALPACA_AUTOPILOT_REFRESH="$OVERRIDE_ALPACA_AUTOPILOT_REFRESH"
fi
if [[ -n "$OVERRIDE_ALPACA_AUTOPILOT_REFRESH_SCRIPT" ]]; then
  export ALPACA_AUTOPILOT_REFRESH_SCRIPT="$OVERRIDE_ALPACA_AUTOPILOT_REFRESH_SCRIPT"
fi
if [[ -n "$OVERRIDE_ALPACA_AUTOPILOT_RUNTIME_DIR" ]]; then
  export ALPACA_AUTOPILOT_RUNTIME_DIR="$OVERRIDE_ALPACA_AUTOPILOT_RUNTIME_DIR"
fi
if [[ -n "$OVERRIDE_ALPACA_PICKS_CSV" ]]; then
  export ALPACA_PICKS_CSV="$OVERRIDE_ALPACA_PICKS_CSV"
fi

export ALPACA_AUTOPILOT_LOCAL_ENV="$CANDIDATE_ENV"

source .venv/bin/activate
FORWARD_ARGS=()
for arg in "$@"; do
  if [[ "$arg" == "--once" ]]; then
    continue
  fi
  FORWARD_ARGS+=("$arg")
done

bash scripts/run_equities_alpaca_monthly_autopilot.sh "${FORWARD_ARGS[@]}"
