#!/usr/bin/env bash
set -euo pipefail

MT5_SETUP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MT5_SETUP_ENV_FILE="${SIGCOPY_SETUP_ENV_FILE:-$MT5_SETUP_ROOT/signal_copy/.env}"
MT5_SETUP_DEFAULT_URL="http://127.0.0.1:22346/mcp"

umask 077
mkdir -p "$(dirname "$MT5_SETUP_ENV_FILE")"

echo "MT5/Bullwaves DEMO read-only setup"
echo "env_file=$MT5_SETUP_ENV_FILE"
echo "This setup keeps execution, live accounts and remote AI disabled."
echo

read -r -s -p "Paste the newly generated MT5 MCP API token: " MT5_SETUP_TOKEN
echo
read -r -p "MCP URL [$MT5_SETUP_DEFAULT_URL]: " MT5_SETUP_URL
MT5_SETUP_URL="${MT5_SETUP_URL:-$MT5_SETUP_DEFAULT_URL}"
read -r -p "Exact demo server name [Bullwaves-Demo]: " MT5_SETUP_SERVER
MT5_SETUP_SERVER="${MT5_SETUP_SERVER:-Bullwaves-Demo}"
read -r -p "Exact demo account login (optional for read-only setup): " MT5_SETUP_LOGIN

if [[ -z "${MT5_SETUP_TOKEN//[[:space:]]/}" ]]; then
  echo "error: token must be non-empty" >&2
  exit 2
fi
if [[ ! "$MT5_SETUP_URL" =~ ^https?://[^[:space:]]+$ ]]; then
  echo "error: MCP URL must be an http(s) URL without spaces" >&2
  exit 2
fi
if [[ -z "${MT5_SETUP_SERVER//[[:space:]]/}" ]]; then
  echo "error: exact demo server name must be non-empty" >&2
  exit 2
fi
if [[ -n "$MT5_SETUP_LOGIN" && ! "$MT5_SETUP_LOGIN" =~ ^[0-9]+$ ]]; then
  echo "error: demo account login must contain digits only" >&2
  exit 2
fi

if [[ -f "$MT5_SETUP_ENV_FILE" ]]; then
  MT5_SETUP_BACKUP="$MT5_SETUP_ENV_FILE.bak_$(date -u '+%Y%m%d_%H%M%S')_$$"
  cp -p "$MT5_SETUP_ENV_FILE" "$MT5_SETUP_BACKUP"
  chmod 600 "$MT5_SETUP_BACKUP"
  echo "backup=$MT5_SETUP_BACKUP"
fi

MT5_SETUP_TMP="$(mktemp "$MT5_SETUP_ENV_FILE.tmp.XXXXXX")"
trap 'rm -f "$MT5_SETUP_TMP"' EXIT INT TERM HUP

if [[ -f "$MT5_SETUP_ENV_FILE" ]]; then
  awk '
    !/^(SIGCOPY_MT5_TOKEN|SIGCOPY_MT5_URL|SIGCOPY_EXECUTION_ENABLE|SIGCOPY_ALLOW_REMOTE_LLM|SIGCOPY_ALLOW_LIVE|SIGCOPY_ALLOWED_SERVERS|SIGCOPY_ALLOWED_ACCOUNT_LOGINS|SIGCOPY_ALLOWED_ACCOUNT_TYPES)=/
  ' "$MT5_SETUP_ENV_FILE" > "$MT5_SETUP_TMP"
fi

{
  printf '\n# DEMO-only values generated by scripts/setup_mt5_demo_env.sh at %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf 'SIGCOPY_MT5_URL=%s\n' "$MT5_SETUP_URL"
  printf 'SIGCOPY_MT5_TOKEN=%s\n' "$MT5_SETUP_TOKEN"
  printf 'SIGCOPY_EXECUTION_ENABLE=0\n'
  printf 'SIGCOPY_ALLOW_REMOTE_LLM=0\n'
  printf 'SIGCOPY_ALLOW_LIVE=0\n'
  printf 'SIGCOPY_ALLOWED_SERVERS=%s\n' "$MT5_SETUP_SERVER"
  printf 'SIGCOPY_ALLOWED_ACCOUNT_LOGINS=%s\n' "$MT5_SETUP_LOGIN"
  printf 'SIGCOPY_ALLOWED_ACCOUNT_TYPES=demo\n'
} >> "$MT5_SETUP_TMP"

chmod 600 "$MT5_SETUP_TMP"
mv "$MT5_SETUP_TMP" "$MT5_SETUP_ENV_FILE"
trap - EXIT INT TERM HUP
chmod 600 "$MT5_SETUP_ENV_FILE"

echo "wrote=$MT5_SETUP_ENV_FILE"
echo "execution=disabled live=disabled remote_ai=disabled"
echo "Next: start MT5 MCP, then run signal_copy/check_live.py manually."
