#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENV_FILE="${ALPACA_LIVE_ENV_FILE:-$ROOT/configs/alpaca_live_v38.env}"
SSH_KEY="${ALPACA_DEPLOY_SSH_KEY:-$HOME/.ssh/by-bot}"
SERVER_TARGET="${ALPACA_DEPLOY_TARGET:-root@64.226.73.119:/root/by-bot/configs/alpaca_live_v38.env}"

umask 077

echo "Alpaca LIVE monthly v38 setup"
echo "env_file=$ENV_FILE"
echo
echo "Use LIVE Trading Dashboard keys only."
echo "Do not paste paper keys here."
echo

read -r -p "Paste Alpaca LIVE API key ID: " API_KEY_ID
read -r -s -p "Paste Alpaca LIVE API secret key: " API_SECRET_KEY
echo

if [[ -z "${API_KEY_ID// }" || -z "${API_SECRET_KEY// }" ]]; then
  echo "error: API key and secret must be non-empty" >&2
  exit 2
fi

read -r -p "Capital cap USD [500]: " CAPITAL_CAP
CAPITAL_CAP="${CAPITAL_CAP:-500}"

if ! [[ "$CAPITAL_CAP" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  echo "error: capital cap must be numeric" >&2
  exit 2
fi

if [[ -f "$ENV_FILE" ]]; then
  BACKUP="$ENV_FILE.bak_$(date +%Y%m%d_%H%M%S)"
  cp -p "$ENV_FILE" "$BACKUP"
  echo "backup=$BACKUP"
fi

cat > "$ENV_FILE" <<EOF
# REAL MONEY - Alpaca monthly v38, capped.
# Generated by scripts/setup_alpaca_live_v38_env.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Keep out of git.
ALPACA_BASE_URL=https://api.alpaca.markets
ALPACA_API_KEY_ID=$API_KEY_ID
ALPACA_API_SECRET_KEY=$API_SECRET_KEY

ALPACA_LIVE_ACCOUNT_ROLE=monthly_v38
ALPACA_LIVE_CONFIRM=MONTHLY_V38_LIVE
ALPACA_LIVE_MAX_CAPITAL_USD=$CAPITAL_CAP
ALPACA_CAPITAL_OVERRIDE_USD=$CAPITAL_CAP

ALPACA_BROKER_PROTECTION_ENABLE=1
ALPACA_BROKER_PROTECTION_REQUIRED=1

# Start disabled. Flip to 1 only after a LIVE dry-run confirms the right account.
ALPACA_SEND_ORDERS=0
EOF

chmod 600 "$ENV_FILE"
echo "wrote=$ENV_FILE"
echo

read -r -p "Deploy this env to $SERVER_TARGET now? [y/N]: " DEPLOY_ANSWER
if [[ "$DEPLOY_ANSWER" =~ ^[Yy]$ ]]; then
  if [[ ! -f "$SSH_KEY" ]]; then
    echo "error: SSH key not found: $SSH_KEY" >&2
    exit 3
  fi
  scp -p -i "$SSH_KEY" "$ENV_FILE" "$SERVER_TARGET"
  echo "deployed=$SERVER_TARGET"
else
  echo "not deployed"
fi

echo
echo "Next: run a LIVE dry-run with ALPACA_SEND_ORDERS=0 before enabling real orders."
